<?php
/* Generated by the CoffeeCup HTML Editor - www.CoffeeCup.com */


// ////////////////////////////////////////////////////////////////
// ////////////////////////////////////////////////////////////////
// BEGIN NATURE EVENTS
// BEGIN NATURE EVENTS
// BEGIN NATURE EVENTS
// ////////////////////////////////////////////////////////////////
// ////////////////////////////////////////////////////////////////

// ////////////////////////////////////////////////////////////////
// START MY RANDOM FALLING TREES  Rings 1501
// ////////////////////////////////////////////////////////////////

 $vv6imalus = rand(1,800); //Random Chance
 
if ($vv6imalus == 1 && $userrow["magicringsid"] != 1501) {  //magicringsid = 1501

    $milline = rand(1,8); //Slot item to leave behind
    $elu = rand(3,15); //Hurt Points Taken
    $palju = $userrow["currenthp"] - $elu;

     $query  = "SELECT slot1id, slot2id, slot3id, slot4id, slot5id, slot6id, slot7id, slot8id, slot1name, slot2name, slot1name, slot4name, slot5name, slot6name, slot7name, slot8name FROM dk_users WHERE id='$userrow[id]'";

      $result = mysql_query($query);

while($row = mysql_fetch_array($result, MYSQL_ASSOC))
{    
$slot1id=$row['slot1id']; 
$slot2id=$row['slot2id']; 
$slot3id=$row['slot3id']; 
$slot4id=$row['slot4id']; 
$slot5id=$row['slot5id']; 
$slot6id=$row['slot6id']; 
$slot7id=$row['slot7id']; 
$slot8id=$row['slot8id']; 

$slot1name=$row['slot1name']; 
$slot2name=$row['slot2name']; 
$slot3name=$row['slot3name'];
$slot4name=$row['slot4name']; 
$slot5name=$row['slot5name']; 
$slot6name=$row['slot6name'];
$slot7name=$row['slot7name']; 
$slot8name=$row['slot8name'];


// ////////////////////////////////////////////////////////////////
// START MILLINE 1
// ////////////////////////////////////////////////////////////////

if ($milline=="1") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Falling Trees Branches<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree01.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>As you were walking through the forest, suddenly with no notice at all. A huge tree falls upon you. Luckily you were not hurt to seriously.  But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>You were trapped by some of the larger Limbs and Branch's. You spend the better part of day light digging and crawling your way from below the rumble of broken tree parts. You discover as you merge from massive tree limbs you may have lost an item you were carrying in your inventory Pack. Your lost item was <font color='#008000'><b>$slot1name</b></font>, which will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                doquery("UPDATE {{table}} 
                SET slot1id='0',slot1name='None' WHERE id=".$userrow["id"], "users");
                doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }


// ////////////////////////////////////////////////////////////////
// END MILLINE 1
// ////////////////////////////////////////////////////////////////

// ////////////////////////////////////////////////////////////////
// START MILLINE 2
// ////////////////////////////////////////////////////////////////

elseif ($milline=="2") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Falling Trees Limbs<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree02.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>As you were walking through the forest, suddenly with no notice at all. A huge tree falls upon you. Luckily you were not hurt to seriously. But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>You were trapped by some of the larger Limbs and Branch's. You spend the better part of day light digging and crawling your way from below the rumble of broken tree parts. You discover as you merge from massive tree limbs you may have lost an item you were carrying in your inventory Pack. Your lost item was <font color='#008000'><b>$slot2name</b></font>, which will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                 doquery("UPDATE {{table}} SET slot2id='0',slot2name='None' WHERE id=".$userrow["id"], "users"); 
                 doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }

// ////////////////////////////////////////////////////////////////
// END MILLINE 2
// ////////////////////////////////////////////////////////////////



// ////////////////////////////////////////////////////////////////
// DISPLAY PAGE for Falling Trees
// ////////////////////////////////////////////////////////////////

display($page, "Falling Trees");
die();
}  }

// ////////////////////////////////////////////////////////////////
// END MY RANDOM Falling Trees Magic Rings 1501
// ////////////////////////////////////////////////////////////////



// ////////////////////////////////////////////////////////////////
// START MY RANDOM Falling Cliff Rocks  Rings 1502
// ////////////////////////////////////////////////////////////////

 $vv6imalus = rand(1,800); //Random Chance
 
if ($vv6imalus == 1 && $userrow["magicringsid"] != 1502) {  //magicringsid = 1502

    $milline = rand(1,8); //Slot item to leave behind
    $elu = rand(3,15); //Hurt Points Taken
    $palju = $userrow["currenthp"] - $elu;

     $query  = "SELECT slot1id, slot2id, slot3id, slot4id, slot5id, slot6id, slot7id, slot8id, slot1name, slot2name, slot1name, slot4name, slot5name, slot6name, slot7name, slot8name FROM dk_users WHERE id='$userrow[id]'";

      $result = mysql_query($query);

while($row = mysql_fetch_array($result, MYSQL_ASSOC))
{    
$slot1id=$row['slot1id']; 
$slot2id=$row['slot2id']; 
$slot3id=$row['slot3id']; 
$slot4id=$row['slot4id']; 
$slot5id=$row['slot5id']; 
$slot6id=$row['slot6id']; 
$slot7id=$row['slot7id']; 
$slot8id=$row['slot8id']; 

$slot1name=$row['slot1name']; 
$slot2name=$row['slot2name']; 
$slot3name=$row['slot3name'];
$slot4name=$row['slot4name']; 
$slot5name=$row['slot5name']; 
$slot6name=$row['slot6name'];
$slot7name=$row['slot7name']; 
$slot8name=$row['slot8name'];


// ////////////////////////////////////////////////////////////////
// START MILLINE 3
// ////////////////////////////////////////////////////////////////

elseif ($milline=="3") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Rumble of Falling Rocks<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree03.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>Exploring near the cliff walls of the nearby forest, you hear a loud rumble - you look up and see rocks of all sizes coming down around you. Luckily you were not hurt to seriously. But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>Trapped by some smaller rocks, you spend the night climbing and digging out of the rumble. You discover as you merge from the rock slide you may have lost an item you were carrying in your inventory Pack. Your lost item was <font color='#008000'><b>$slot3name</b></font>, which will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                 doquery("UPDATE {{table}} SET slot3id='0',slot3name='None' WHERE id=".$userrow["id"], "users"); 
                 doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }

// ////////////////////////////////////////////////////////////////
// END MILLINE 3
// ////////////////////////////////////////////////////////////////


// ////////////////////////////////////////////////////////////////
// START MILLINE 4
// ////////////////////////////////////////////////////////////////

elseif ($milline=="4") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Falling Cliff Rocks<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree03.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>Exploring near the cliff walls of the nearby forest, you hear a loud rumble - you look up and see rocks of all sizes coming down around you. Luckily you were not hurt to seriously. But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>Trapped by some smaller rocks, you spend the night climbing and digging out of the rumble. You discover as you merge from the rock slide you may have lost an item you were carrying in your inventory Pack. Your lost item was <font color='#008000'><b>$slot4name</b></font>, which will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                 doquery("UPDATE {{table}} SET slot4id='0',slot4name='None' WHERE id=".$userrow["id"], "users"); 
                 doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }

// ////////////////////////////////////////////////////////////////
// END MILLINE 4
// ////////////////////////////////////////////////////////////////


// ////////////////////////////////////////////////////////////////
// DISPLAY PAGE for Falling Cliff Rocks
// ////////////////////////////////////////////////////////////////

display($page, "Falling Cliff Rocks");
die();
}  }

// ////////////////////////////////////////////////////////////////
// END MY RANDOM Falling Cliff Rocks Magic Rings 1502
// ////////////////////////////////////////////////////////////////






// ////////////////////////////////////////////////////////////////
// START MY RANDOM Storm Waves  Rings 1503
// ////////////////////////////////////////////////////////////////

 $vv6imalus = rand(1,800); //Random Chance
 
if ($vv6imalus == 1 && $userrow["magicringsid"] != 1503) {  //magicringsid = 1503

    $milline = rand(1,8); //Slot item to leave behind
    $elu = rand(3,15); //Hurt Points Taken
    $palju = $userrow["currenthp"] - $elu;

     $query  = "SELECT slot1id, slot2id, slot3id, slot4id, slot5id, slot6id, slot7id, slot8id, slot1name, slot2name, slot1name, slot4name, slot5name, slot6name, slot7name, slot8name FROM dk_users WHERE id='$userrow[id]'";

      $result = mysql_query($query);

while($row = mysql_fetch_array($result, MYSQL_ASSOC))
{    
$slot1id=$row['slot1id']; 
$slot2id=$row['slot2id']; 
$slot3id=$row['slot3id']; 
$slot4id=$row['slot4id']; 
$slot5id=$row['slot5id']; 
$slot6id=$row['slot6id']; 
$slot7id=$row['slot7id']; 
$slot8id=$row['slot8id']; 

$slot1name=$row['slot1name']; 
$slot2name=$row['slot2name']; 
$slot3name=$row['slot3name'];
$slot4name=$row['slot4name']; 
$slot5name=$row['slot5name']; 
$slot6name=$row['slot6name'];
$slot7name=$row['slot7name']; 
$slot8name=$row['slot8name'];


// ////////////////////////////////////////////////////////////////
// START MILLINE 5
// ////////////////////////////////////////////////////////////////

elseif ($milline=="5") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Storm Water Tides<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree05.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>Exploring the coastline of this strange new world, a sudden storm hits and the waves grow in height and quickly overwhelm you. Luckily you were not hurt to seriously. But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>With the new morning light, you take stock of yourself, as you recover from massive waves you may have lost an item you were carrying in your inventory Pack. Your lost item was <font color='#008000'><b>$slot5name</b></font>, which will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                 doquery("UPDATE {{table}} SET slot5id='0',slot5name='None' WHERE id=".$userrow["id"], "users"); 
                 doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }

// ////////////////////////////////////////////////////////////////
// END MILLINE 5
// ////////////////////////////////////////////////////////////////


// ////////////////////////////////////////////////////////////////
// START MILLINE 6
// ////////////////////////////////////////////////////////////////

elseif ($milline=="6") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Massive Storm Waves<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree05.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>Exploring the coastline of this strange new world, a sudden storm hits and the waves grow in height and quickly overwhelm you. Luckily you were not hurt to seriously. But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>With the new morning light, you take stock of yourself, as you recover from massive waves you may have lost an item you were carrying in your inventory Pack. Your lost item was <font color='#008000'><b>$slot6name</b></font>, which will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                 doquery("UPDATE {{table}} SET slot6id='0',slot6name='None' WHERE id=".$userrow["id"], "users"); 
                 doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }

// ////////////////////////////////////////////////////////////////
// END MILLINE 6
// ////////////////////////////////////////////////////////////////


// ////////////////////////////////////////////////////////////////
// DISPLAY PAGE for Storm Waves
// ////////////////////////////////////////////////////////////////

display($page, "Storm Waves");
die();
}  }

// ////////////////////////////////////////////////////////////////
// END MY RANDOM Storm Waves Magic Rings 1503
// ////////////////////////////////////////////////////////////////







// ////////////////////////////////////////////////////////////////
// START MY RANDOM Hot Sands and No Water  Rings 1504
// ////////////////////////////////////////////////////////////////

 $vv6imalus = rand(1,800); //Random Chance
 
if ($vv6imalus == 1 && $userrow["magicringsid"] != 1504) {  //magicringsid = 1504

    $milline = rand(1,8); //Slot item to leave behind
    $elu = rand(3,15); //Hurt Points Taken
    $palju = $userrow["currenthp"] - $elu;

     $query  = "SELECT slot1id, slot2id, slot3id, slot4id, slot5id, slot6id, slot7id, slot8id, slot1name, slot2name, slot1name, slot4name, slot5name, slot6name, slot7name, slot8name FROM dk_users WHERE id='$userrow[id]'";

      $result = mysql_query($query);

while($row = mysql_fetch_array($result, MYSQL_ASSOC))
{    
$slot1id=$row['slot1id']; 
$slot2id=$row['slot2id']; 
$slot3id=$row['slot3id']; 
$slot4id=$row['slot4id']; 
$slot5id=$row['slot5id']; 
$slot6id=$row['slot6id']; 
$slot7id=$row['slot7id']; 
$slot8id=$row['slot8id']; 

$slot1name=$row['slot1name']; 
$slot2name=$row['slot2name']; 
$slot3name=$row['slot3name'];
$slot4name=$row['slot4name']; 
$slot5name=$row['slot5name']; 
$slot6name=$row['slot6name'];
$slot7name=$row['slot7name']; 
$slot8name=$row['slot8name'];


// ////////////////////////////////////////////////////////////////
// START MILLINE 7
// ////////////////////////////////////////////////////////////////

elseif ($milline=="7") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Hot Sands and Near Death<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree07.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>You have been walking for a long long time, the thirst and heat has scrambled you mind. You fall into a deep coma and near death. Luckily after a few hours you wake up dazed and found some water near, not hurt to seriously. But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>As you rest and gain your strength, You discover you may have lost an item you were carrying in your inventory Pack. If so, Your lost item was <font color='#008000'><b>$slot7name</b></font>, will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                 doquery("UPDATE {{table}} SET slot7id='0',slot7name='None' WHERE id=".$userrow["id"], "users"); 
                 doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }

// ////////////////////////////////////////////////////////////////
// END MILLINE 7
// ////////////////////////////////////////////////////////////////


// ////////////////////////////////////////////////////////////////
// START MILLINE 8
// ////////////////////////////////////////////////////////////////

elseif ($milline=="8") { 
$page="<table width=100%><tr><td><center><h3 class=title>Exploring - Hot Sands and No Water<h3></center><tr><td>

<center><table width=450><tr><td><img src='images/deadtree/DeadTree07.png' border='3' align='center' width='450'></td></tr>
<tr><td><br>You have been walking for a long long time, the thirst and heat has scrambled you mind. You fall into a deep coma and near death. Luckily after a few hours you wake up dazed and found some water near, not hurt to seriously. But Fortune may have saved your life, but you lost <font color='#008000'><b>$elu Hit Points</b></font> leaving you with <font color='#008000'>$palju Hit Points</font> out of your <font color='#008000'>Maximum Hit Points of ".$userrow["maxhp"]."</font>.

<br><br>As you rest and gain your strength, You discover you may have lost an item you were carrying in your inventory Pack. If so, Your lost item was <font color='#008000'><b>$slot8name</b></font>, will be missed greatly.</td></tr>

<tr><td><br><br><center><a href=index.php class=myButton2>Continue exploring</a></center></td></tr></table>
</td></tr></table></center><br><br>"; 

                 doquery("UPDATE {{table}} SET slot8id='0',slot8name='None' WHERE id=".$userrow["id"], "users"); 
                 doquery("UPDATE {{table}} SET currenthp='$palju' WHERE id=".$userrow["id"], "users");  }

// ////////////////////////////////////////////////////////////////
// END MILLINE 8
// ////////////////////////////////////////////////////////////////


// ////////////////////////////////////////////////////////////////
// DISPLAY PAGE for Hot Sands and No Water
// ////////////////////////////////////////////////////////////////

display($page, "Hot Sands and No Water");
die();
}  }

// ////////////////////////////////////////////////////////////////
// END MY RANDOM Hot Sands and No Water Magic Rings 1504
// ////////////////////////////////////////////////////////////////





?>
